---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: <BRANCH_NAME>
spec:
  selector:
    matchLabels:
      app: <BRANCH_NAME>
  replicas: 4
  template:
    metadata:
      labels:
        app: <BRANCH_NAME>
    spec:
      containers:
      - name: <BRANCH_NAME>
        image: harbor.dominos.com/dc3-prod/<BRANCH_NAME>:<TAG>
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: <BRANCH_NAME>
  labels:
    run: <BRANCH_NAME>
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: <BRANCH_NAME>
