---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: <BRANCH_NAME>
  namespace: <NAMESPACE>
spec:
  selector:
    matchLabels:
      app: <BRANCH_NAME>
  replicas: <REPLICAS>
  template:
    metadata:
      labels:
        app: <BRANCH_NAME>
    spec:
      containers:
      - name: <BRANCH_NAME>
        image: harbor.dominos.com/dc3-prod/<BRANCH_NAME>:<TAG>
        resources:
          limits:
            cpu: 1000m
            memory: 500Mi
          requests:
            cpu: 500m
            memory: 250M
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: dc3-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: <BRANCH_NAME>
  labels:
    run: <BRANCH_NAME>
  namespace: <NAMESPACE>
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: <BRANCH_NAME>
